# Usa a imagem oficial do Node.js
FROM node:18

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos de dependência
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta da aplicação (3000)
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
